config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index' # change from get to root and the "/" to "#", changes the default index page
  resources :posts
  resources :users, only: [:index]
  resources :comments, only: [:create, :index]

  get  '/contact'      => 'contact#index'
  post '/contact/send' => 'contact#send_email'

  get '/comments/:id/toggle_status' => 'comments#toggle_status', as: :comment_toggle_status

  # kalw mia me8odo, ara 8elw ena endpoint, alla dn 8elw na fortwnei ena adeio template, opote
  # anti gia html kanw xhr is js

  # namespace gia ton api::posts_controller
  namespace :api do
    resources :posts
  end

  namespace :admin do
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  scope :latest, -> { order(updated_at: :desc) }
  scope :approved, -> { where(approved: true) }

  def approved?
    approved
  end
end

# Comment.all.each do |comment|
#   comment.update_attributes(approved: false) unless comment.approved?
# end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :user

  validates :title, presence: true

  def is_new?
   created_at >= Date.today
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments

  enum role: {
    user: 0,
    admin: 1
  }
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout "admin"

  before_action :authenticate_user!
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  def index
    @posts = Post.all
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ActionController::Metal # ::Metal ειναι modules
  include AbstractController::Rendering
  include ActionView::Rendering
  include ActionController::Rendering
  include ActionController::Renderers::All
  include ActionController::Serialization
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::BaseController
  def index
    # den xreiazetai to @posts , dn exoume view
    render json: Post.all.order(created_at: :desc), root: true, each_serializer: PostSerializer # <- vgainei ena epipedo e3w
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # hooks
  before_action :fetch_comments, only: [:index, :toggle_status]

  def create
    # to post.id mporoume na to valoume kai sti forma
    # i mporoume na to valoume mesa sti new (posts controller)
    @comment = Comment.create(comment_params)
  end

  def index
    # @comments = Comment.all <- trexei apo to before_action
  end

  def toggle_status
    # ta rails sto telos tis methodou kaloun tin render kai prospa8ei na vrei to view,
    # edw tou leme specific kane render ena js code
    # render js: "alert('ok')"

    # @comments = Comment.all <- trexei apo to before_action

    # meta to action ston controller, prepei to model na alla3ei to status tis vasis (approved i oxi)

    # vriskw to comment
    @comment = Comment.find(params[:id])
    # @comment.approved = !@comment.approved
    @comment.toggle!(:approved)
  end

  private
  def comment_params
    params.require(:comment).permit(:author, :body, :post_id)
  end

  def fetch_comments
    @comments = Comment.all
  end
end

# klikarw
# pairnw xhr
# apantaei o controller me JS (rendearei ena view)
# sto js allazoume to dom element
# paei sti toggle_status
# vriskoume to comment
# before_action trexei prin tis methodous tou controller
#

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end

  def send_email
    ApplicationMailer.contact_form(params["Email"], params["Name"], params["Message"]).deliver
    redirect_to contact_path, notice: "Message sent!"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.first

    respond_to do |format|
      format.html do
        @post = Post.new #-> gia tin for form pou zei stin index
        @posts = Post.all.order(created_at: :desc)
      end
      format.json do
        @posts = Post.all.order(created_at: :desc)
        render json: @posts # koitaei apo pio modelo erxetai to @posts
      end
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new # not persisted, just to initiate, enw i create einai ayto poy vlepoyme sti vasi
  end

  def edit
    @post = Post.find(params[:id])
    # i edit einai auto poy vlepoyme, i update einai i kainoyria edit poy eiani sti vasi
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)

    redirect_to '/posts'
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)

    if @post.persisted? # oxi @post.save epistrefei true or false
      respond_to do |format|
        format.html do
          redirect_to posts_path, notice: "Post succesfully created!" # <- use helper for paths
        end

        format.js do
          @posts = Post.all.order(created_at: :desc)
        end
      end
    end
  end

  def destroy
    post = Post.find(params[:id]) # den xreiazetai to @post giati to diagrafoume, den 8a to 3anazitisoyme
    post.destroy # an eixe delete 8a pigaine kai 8a to esvine apo ti vasi, to destroy akolou8ei ta assosionations. px an eixe comments to post, kai kaname delete to post, ta comments 8a mename orfana. Me to "destroy" svinoun kai ta comments(dependent: :destroy)

    # if post.destroy
    #   redirect_to '/posts' # redirect_to posts_path # zitaw ena action me to direct, enw me to render zitaw ena view
    # end

    # if js/ajax
    respond_to do |format| # to respond einai san to done tis js enos ajax request
      format.html do
        redirect_to posts_path
      end

      format.js do
        @posts = Post.all.order(created_at: :desc)
      end
    end
  end

  private # or protect (apo tin klassi poy eimaste kai katw), auti i methodos einai prosvasimi mono apo to idio to instance toy sugkekrimenou object

  def post_params
    params.require(:post).permit(:title, :text) # an kalesoume tin post_params 8a mas epistrepsei mono ton titlo kai to text pou exei vrei mesa sto params[title], params[text]
    # params.require(:post).permit!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! # user is the resource

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.persisted? # oxi @user.save epistrefei true or false
      respond_to do |format|
        format.html do
          redirect_to user_path, notice: "User succesfully created!" # <- use helper for paths
        end

        format.js do
          @users = User.all.order(created_at: :desc)
        end
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_email(user)
    "<p>#{user.email}</p>" if user && user.email
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/posts/index.html.erb
<% @posts.each do |post| %>
  <%= post.title %>
  <%= post.text %>
<% end %>

app/views/comments/_comments.html.erb
<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.id %></td>
    <td><%= comment.body %></td>
    <td><%= comment.created_at %></td>
    <td><%= comment.approved? %></td>
    <td>
      <% if comment.approved? %>
        <%#= katw peranw to comment, anti gia comment.id, einai to idio  %>
        <%= link_to "reject", comment_toggle_status_path(comment), class: "button is-danger", remote: true %>
        <%#= me remote true kanei Processing by CommentsController#toggle_status as JS, opote prepei na xrisimopoiisw JS template  %>
      <% else %>
        <%= link_to "approve", comment_toggle_status_path(comment), class: "button is-primary", remote: true %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/comments/create.html.erb
<p>Success!!</p>

app/views/comments/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>id</th>
      <th>comment</th>
      <th>created_at</th>
      <th>approved</th>
      <th>actions</th>
    </tr>
  </thead>

  <tbody id="js-comments-body">
    <%= render 'comments' %>
  </tbody>
</table>

app/views/comments/toggle_status.js.erb
$('#js-comments-body').html("<%= j render partial: 'comments' %>")

app/views/contact/index.html.erb
<div class="columns">
  <div class="column">
    <%= form_tag contact_send_path do %>
      <p><%= text_field_tag 'Email', nil, placeholder: "Email" %></p>
      <p><%= text_field_tag 'Name', nil, placeholder: "Name" %></p>
      <p><%= text_area_tag 'Message', nil, placeholder: "Message" %></p>
      <div><%= submit_tag 'Save' %></div>
    <% end %>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>

    <nav class="navbar" role="navigation" aria-label="main navigation">

    </nav>

    <div class="container is-fluid">
      <div class="notification">
        This container is <strong>centered</strong> on desktop.
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>

    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
         <img src="https://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
        </a>
        <%= link_to "Home", root_path, class: "navbar-item" %>
        <%= link_to "Posts", posts_path, class: "navbar-item" %>
        <%= link_to "New Post", new_post_path, class: "navbar-item" %>
        <%= link_to "Remote Posts", posts_path, class: "navbar-item", remote: true %>
        <%= link_to "Contacts", contact_path, class: "navbar-item" %>
        <%= link_to "Comments", comments_path, class: "navbar-item" %>

        <% if user_signed_in? %>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              Welcome <%= current_user.email %>
            </a>

            <div class="navbar-dropdown is-pulled-right">
              <%= link_to 'My account', edit_user_registration_path, class: 'navbar-item' %>
              <hr class="navbar-divider">
              <%= link_to 'Sign out', destroy_session_path(:user), method: :delete, class: 'navbar-item' %>
            </div>
          </div>
        <% else %>
          <%= link_to 'Sign in', user_session_path, class: 'navbar-item' %>
        <% end %>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <%= raw(user_email(@user)) %>
    </nav>

    <div class="container is-fluid">
      <div class="notification">
        This container is <strong>centered</strong> on desktop.
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_edit_form.html.erb
<form class="" action="/posts/<%= @post.id %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <div class="">
    <label>Post title:</label>
    <input type="text" name="title" value= "<%= @post.title %>">
  </div>

  <div class="">
    <label>Content:</label>
    <textarea name="text" rows="8" cols="80"><%= @post.text %></textarea>
  </div>

  <div class="">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" name="" value="Submit">
  </div>
</form>

app/views/posts/_list.html.erb
<% @posts.each do |post| %>
  <div class="box">
    <article class="media">
      <div class="media-left">
        <figure class="image is-64x64">
          <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <strong><%= post.id %></strong> <small><%= post.title %></small> <small><p><%= post.created_at.strftime("%Y-%m-%d") %></p> <!-- or post.created_at.to_date --></small>
            <br>
            <p><%= post.text %></p>
          </p>
        </div>
      </div>
    </article>

    <p>
      <%= link_to edit_post_path(post) do %>
        Edit
      <% end %> |
      <%= link_to "Delete", post, method: :delete, data: { confirm: "Are you sure?" } %> <!-- to data vrisketai sto rails-ujs -->
      <%= link_to "Delete me js", post, method: :delete, data: { confirm: "Are you sure?" }, remote: true %> <!-- to data vrisketai sto rails-ujs -->
    </p>
  </div>
<% end %>

app/views/posts/_new_form.html.erb
<% if @post && @post.errors.any? %>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @post, remote: true do |f| %>
  <!-- to f antiproswpeuei ena instance (object) tis formas mas -->
  <p>
    <%= f.text_field :title, placeholder: "Title", class: "input" %> <!-- xtizei to name="post[title]" f to post, title to value -->
  </p>

  <p>
    <%= f.text_area :text, placeholder: "Message", class: "textarea" %>
  </p>

  <p>
    <%= f.submit "Send", class: "button" %>
  </p>
<% end %>

<!-- <form class="" action="/posts" method="post">
  <div class="">
    <label>Post title:</label>
    <input type="text" name="post[title]" value="">
  </div>

  <div class="">
    <label>Content:</label>
    <textarea name="post[text]" rows="8" cols="80"></textarea>
  </div>

  <div class="">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" name="" value="Submit">
  </div>
</form> -->

app/views/posts/create.html.erb
<h2>Create post</h2>

<%= render "new_form" %>

app/views/posts/create.js.erb
$('.list').html('<%= j render "list" %>');

app/views/posts/destroy.js.erb
$('.list').html('<%= j render "list" %>');

app/views/posts/edit.html.erb
<h2>Edit post</h2>

<%= render "edit_form" %>

app/views/posts/index.html.erb
<div class="columns">
  <div class="column">
    <div class="list">
      <%= render 'list' %>
    </div>
  </div>

  <div class="column">
    <%= render 'new_form' %>
  </div>
</div>

app/views/posts/index.js.erb
$('.container').html('<%= j render "list" %>');

app/views/posts/new.html.erb
<h2>New post</h2>

<%= render "new_form" %>

app/views/posts/show.html.erb
This is the show page.

<h2> <%= @post.title %> </h2>
<p> <%= @post.text %> </p>

<h3>Comments (<%= @post.comments.approved.size %>) </h3>

<ul>
  <% @post.comments.latest.approved.each_with_index do |c| %>
    <li> <%= c.id %> | <%= c.body %> </li>
  <% end %>
</ul>

<!-- form_tag xrisimopoiw otan 8elw kati custom, plain -->
<%= form_for @comment do |c| %>

  <%= c.hidden_field :post_id, value: @post.id %>

  <%= hidden_field_tag :post_id, value: @post.id %>

  <p>
    <%= c.text_field :author, placeholder: "Author" %>
  </p>

  <p>
    <%= c.text_area :body, placeholder: "Your comment" %>
  </p>

  <p>
    <%= c.submit "Send message", class: "button" %>
  </p>
<% end %>

app/views/posts/update.html.erb
<h2>Edit post</h2>

<%= render "edit_form" %>

app/views/users/index.html.erb
<h3>All users</h3>

app/views/users/new.html.erb
<% if @user && @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user, remote: true do |f| %>
  <!-- to f antiproswpeuei ena instance (object) tis formas mas -->
  <p class="field">
    <label class="label" for="username">Username</label>
    <%= f.text_field :username, placeholder: "email", class: "input" %> <!-- xtizei to name="user[title]" f to user, title to value -->
  </p>

  <p class="field">
    <label class="label" for="role">Role</label>
    <%= f.text_field :role, placeholder: "role", class: "input" %>
  </p>

  <p class="field">
    <%= f.submit "Create", class: "button is-link" %>
  </p>
<% end %>